name: Verify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-android-jvm-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle build
        run: ./gradlew detekt

      - name: Build Android target
        run: ./gradlew composeApp:assembleDebug

      - name: Build Jvm target
        run: ./gradlew composeApp:packageDistributionForCurrentOS

      - name: Build Web target
        run: ./gradlew composeApp:wasmJsBrowserDistribution
